version: "3.8"

services:
  mysql:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: issue-tracker
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
